INSERT INTO [Cities] ([Name],[NameRaw],[GtCodeSale],[GtCodeRent]) VALUES ('Warszawa','warszawa','v1c9073l3200008a1dwp','v1c9008l3200008a1dwp')
INSERT INTO [Cities] ([Name],[NameRaw],[GtCodeSale],[GtCodeRent]) VALUES ('Poznañ','poznan','v1c9073l3200366a1dwp','v1c9008l3200366a1dwp')
INSERT INTO [Cities] ([Name],[NameRaw],[GtCodeSale],[GtCodeRent]) VALUES ('Kraków','krakow','v1c9073l3200208a1dwp','v1c9008l3200208p')
INSERT INTO [Cities] ([Name],[NameRaw],[GtCodeSale],[GtCodeRent]) VALUES ('Wroc³aw','wroclaw','v1c9073l3200114a1dwp','v1c9008l3200114p')

INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (0,'otodom',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (1,'olx',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (2,'adresowo',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (3,'domiporta',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (4,'gratka',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (5,'morizon',1)
INSERT INTO [Sites] ([Type],[Name],[IsActive]) VALUES (6,'gumtree',1)

INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Bemowo', 'bemowo', 'v1c9073l3200009a1dwp1', '', '367')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Bia³o³êka', 'bialoleka', 'v1c9073l3200010a1dwp1', '', '365')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Bielany', 'bielany', 'v1c9073l3200011a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Mokotów', 'mokotow', 'v1c9073l3200012a1dwp1', '', '353')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Ochota', 'ochota', 'v1c9073l3200013a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Praga Po³udnie', 'praga-poludnie', 'v1c9073l3200015a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Praga Pó³noc', 'praga-pó³noc', 'v1c9073l3200014a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Rembertów', 'rembertow', 'v1c9073l3200016a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Œródmieœcie', 'srodmiescie', 'v1c9073l3200017a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Targówek', 'targowek', 'v1c9073l3200018a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Ursus', 'ursus', 'v1c9073l3200019a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Ursynów', 'ursynow', 'v1c9073l3200020a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Wawer', 'wawer', 'v1c9073l3200021a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Weso³a', 'wesola', 'v1c9073l3200022a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Wilanów', 'wilanow', 'v1c9073l3200023a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'W³ochy', 'wlochy', 'v1c9073l3200024a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, 'Wola', 'wola', 'v1c9073l3200025a1dwp1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, GtCodeSale, GtCodeRent, OlxId) VALUES (1, '¯oliborz', 'zoliborz', 'v1c9073l3200026a1dwp1', '', '')

INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Stare Miasto', 'stare-miasto', '273', '-G', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Grzegórzki', 'grzegorzki', '279', '-z', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Pr¹dnik Czerwony', 'pradnik-czerwony', '277', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Pr¹dnik Bia³y', 'pradnik-bialy', '275', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Krowodrza', 'krowodrza', '255', '-4', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Bronowice', 'bronowice', '259', '-wielkie', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Zwierzyniec', 'zwierzyniec', '257', '-L', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Dêbniki', 'debniki', '261', '-o', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, '£agiewniki-Borek Fa³êcki', 'lagiewniki', '265', '-a', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Swoszowice', 'swoszowice', '267', '-1', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Podgórze Duchackie', 'podgorze-duchackie', '269', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Bie¿anów-Prokocim', 'biezanow', '271', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Podgórze', 'podgorze', '263', '-fH', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Czy¿yny', 'czyzyny', '283', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Mistrzejowice', 'mistrzejowice', '463', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Bieñczyce', 'bienczyce', '285', '-E', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Wzgórza Krzes³awickie', 'wzgorza-krzeslawickie', '281', '', '', '')
INSERT INTO Districts (CityId, Name, NameRaw, OlxId, AdrId, GtCodeSale, GtCodeRent) VALUES (3, 'Nowa Huta', 'nowa-huta', '287', '-B', '', '')